### ISSUE TITLE
Initialization Speed

### ISSUE THREAD

**Issue by OxfordTrail** [tomayac/local-reverse-geocoder#23]
In the readme file, under **A Word on Initialization Speed**, you've mentioned that it download arounds 300MB of data which is later unzipped and cached.  

Is it possible to restrict downloading of all data during initiatlization? Use case : If one has to lookup location for a particular country, say India, one can only download required data for that country. This will reduce the initialisation speed.

**Comment by tomayac** [comment]
(Thanks for opening the Issue and sorry for the delayed reply, I was traveling.)

Looking at the [GeoNames README](http://download.geonames.org/export/dump/readme.txt), this looks possible by downloading the desired `XX.zip` files instead of the `allCountries.zip` file. 

I currently don't have the time to work on this, but am more than happy to merge a Pull Request if you (or someone else) wants to work on this.

**Comment by tomayac** [comment]
Fixed via https://github.com/tomayac/local-reverse-geocoder/pull/41.
